# Generated by Django 5.2.4 on 2025-09-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_panel', '0002_delete_companyinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='会社名')),
                ('postal_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='郵便番号')),
                ('address', models.CharField(blank=True, max_length=500, null=True, verbose_name='住所')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('description', models.TextField(blank=True, null=True, verbose_name='会社説明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '会社情報',
                'verbose_name_plural': '会社情報',
            },
        ),
    ]
