# Generated by Django 5.2.4 on 2025-07-31 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_birth_year_user_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='job',
        ),
    ]
