# Generated by Django 5.2.4 on 2025-07-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
