# Generated by Django 5.2.4 on 2025-09-09 00:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_review_created_at_review_updated_at_review_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='review',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='表示/非表示'),
        ),
    ]
